
# 不同的开发环境，不同的微服务名字
spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: TestApp1
---
spring:
  profiles: test   #测试环境
  application: 
    name: TestApp2
---
